### ISSUE TITLE
This repo is in the wrong place it should have been in Plantandfood not Actinidia

### ISSUE THREAD

**Issue by rosscrowhurst** [Actinidia/Hort16AxRussell#1]
@jtahir You have created this repo in "https://github.com/Actinidia" - it in my opinion should have been created in "https://github.com/PlantandFoodResearch" where it would have been accessible to everyone. The whole of "https://github.com/Actinidia" should be moved to https://github.com/PlantandFoodResearch so that we only have one upper level organization.

**Comment by cfljam** [comment]
discussed w Jibran and closed
